name: Release
on:
  push:
    tags:
      - v*
  # Manual dispatch for testing
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish package
        run: ./gradlew packageWinX64 packageLinuxX64 -PliftoffVersion="${LIFTOFF_VERSION:1}"
        env:
            LIFTOFF_VERSION: ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/construo/dist/*
            build/libs/*
